vegefoods/cart/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    # path('', views.CartPage.as_view(), name='cart'),
    path('', views.view_cart, name='cart'),
    url(r"add/(?P<pk>\d+)(?P<qnt>\d+)/$",views.add_to_cart,name="add_to_cart"),
    path('wishlist/', views.WhishlistPage.as_view(), name='wishlist'),
    path('thanks/', views.ThanksPage, name='thanks'),
    url(r"remove/(?P<pk>\d+)/$",views.remove_from_cart.as_view(),name="remove"),
    url(r"addone/(?P<pk>\d+)/(?P<pg>\d+)/$",views.add_one_to_cart.as_view(),name="addone"),
    url(r"addwish/(?P<pk>\d+)/(?P<pg>\d+)/$",views.add_to_wishlist.as_view(),name="addwish"),
]

vegefoods/shop/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


app_name = 'shop'

urlpatterns = [
    path('', views.ShopPage, name='shop'),
    # path('single_product/', views.ShopPage.as_view(), name='single_product'),
    url(r"single_product/(?P<pk>\d+)/$",views.SingleProduct,name="single_product"),
]

vegefoods/vegefoods/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage, name='home'),
    path('admin/', admin.site.urls),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('checkout/', views.checkoutPage.as_view(), name='checkout'),
    path('contact/', views.contactPage.as_view(), name='contact'),
    path('shop/', include('shop.urls', namespace="shop")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
]

vegefoods/shop/models.py
from django.db import models



KIND_CHOICES = (
    ('vegetables','Vegetables'),
    ('fruits', 'Fruits'),
    ('juice','Juice'),
    ('dried','Dried'),
)
class Vegtables(models.Model):
    title = models.CharField(max_length=255, unique=True)
    kind = models.CharField(max_length=10, choices=KIND_CHOICES, default='green')
    prise = models.DecimalField(max_digits=6, decimal_places=2)
    Discount = models.PositiveIntegerField(default=0)
    detail = models.TextField(blank=True, default='')
    count = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to = 'static/media/vegtables', default = 'static/media/vegtables/no-img.jpg')

    def __str__(self):
        return self.title

    def discount_prise(self):
        return (self.prise * (100 - self.Discount))/100

    class Meta:
        ordering = ["title"]

vegefoods/shop/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView
from django.http import Http404
from shop.models import Vegtables
from cart.models import Wishlist
from . import models

# class ShopPage(ListView):
#     model = Vegtables
#     template_name = 'shop.html'

# class SingleProduct(ListView):
#     model = Vegtables
#     template_name = 'single_product.html'

def ShopPage(request):
    vegtable = Vegtables.objects.all
    wishlist = Wishlist.objects.all
    args = {'vegtable':vegtable, 'wishlist':wishlist}
    return render(request,'shop.html',args)

def SingleProduct(request, pk=None):
    wishlist = Wishlist.objects.all
    if pk:
        vegtable = Vegtables.objects.all
        args = {'vegtable':vegtable, 'pk':pk, 'wishlist':wishlist}
        return render(request,'single_product.html',args)

    else:
        args = {'wishlist':wishlist}
        return render(request,'shop.html',args)

vegefoods/shop/templates/shop.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <section class="ftco-section">
    	<div class="container">
    		{% comment %} <div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
    					<li><a href="#">Vegetables</a></li>
    					<li><a href="#">Fruits</a></li>
    					<li><a href="#">Juice</a></li>
    					<li><a href="#">Dried</a></li>
    				</ul>
    			</div>
    		</div> {% endcomment %}
    		<div class="row">
			{% for Vegtables in vegtable %}
				<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="{% url 'shop:single_product' pk=Vegtables.pk %}" class="img-prod"><img class="img-fluid" src="/{{ Vegtables.image }}" alt="Colorlib Template">
						{% if Vegtables.Discount > 0 %}
    						<span class="status">{{ Vegtables.Discount }}%</span>
						{% endif %}
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">{{ Vegtables.title }}</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
								{% if Vegtables.Discount > 0 %}
		    						<p class="price"><span class="mr-2 price-dc">${{ Vegtables.prise }}</span><span class="price-sale">${{ Vegtables.discount_prise }}</span></p>
								{% else %}
									<p class="price"><span>${{ Vegtables.prise }}</span></p>
								{% endif %}
		    					</div>
	    					</div>
	    					<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="{% url 'shop:single_product' pk=Vegtables.pk %}" class="add-to-cart d-flex justify-content-center align-items-center text-center">
	    								<span><i class="ion-ios-menu"></i></span>
	    							</a>
	    							<a href="{% url 'cart:addone' pk=Vegtables.pk pg=2 %}" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
	    							</a>
									{% for Whislist in wishlist %}
										{% if user ==  Whislist.user %}
											{% if Vegtables ==  Whislist.vegtable %}
												{% if Whislist.wish ==  True %}
													<style>
														a[href="{% url 'cart:addwish' pk=Vegtables.pk pg=2 %}"] {
															color:#CB4335 !important;
														}
													</style>
												{% endif %}
											{% endif %}
										{% endif %}
									{% endfor %}
	    							<a href="{% url 'cart:addwish' pk=Vegtables.pk pg=2 %}" class="heart d-flex justify-content-center align-items-center ">
	    								<span><i class="ion-ios-heart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
				{% endfor %}
    			
    		</div>
    		<div class="row mt-5">
          {% comment %} <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div> {% endcomment %}
        </div>
    	</div>
    </section>

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
{% endblock content %}

vegefoods/shop/templates/single_product.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<section class="ftco-section">
    	<div class="container">
    		<div class="row">
            {% for Vegtables in vegtable %}
				{% if Vegtables.pk|add:"0" == pk|add:"0" %}
                    <div class="col-lg-6 mb-5 ftco-animate">
                        <a href="/{{ Vegtables.image }}" class="image-popup"><img src="/{{ Vegtables.image }}" class="img-fluid" alt="Colorlib Template">
                        {% if Vegtables.Discount > 0 %}
                                <span class="status" style="position: absolute; top: 0px; left: 0px; color: rgb(255, 255, 255); font-weight: 300; font-size: 12px; padding: 2px 10px; background: rgb(130, 174, 70);">{{ Vegtables.Discount }}%</span>
                            {% endif %}
                                <div class="overlay"></div>
                        </a>
                    </div>
                    <div class="col-lg-6 product-details pl-md-5 ftco-animate">
                        <h3>{{ Vegtables.title }}</h3>

                        {% if Vegtables.Discount > 0 %}
                            <p class="price"><span class="mr-2 price-dc" style="text-decoration: line-through;color: #b3b3b3;">${{ Vegtables.prise }}</span><span class="price-sale">${{ Vegtables.discount_prise }}</span></p>
                        {% else %}
                            <p class="price"><span>${{ Vegtables.prise }}</span></p>
                        {% endif %}
                        
                        <p>{{ Vegtables.detail }}</p>

                        <p style="color:black;margin-bottom:0px">Quantity:</p>
                        <input id="num" style="padding-left:5px" type="number" name="count" value="1" class="vIntegerField" min="1" required="" onKeyDown="return false">
                            <br><br>
                        <p><a id="link" href="{% url 'cart:add_to_cart' pk=Vegtables.pk qnt=1 %}" class="btn btn-black py-3 px-5">Add to Cart</a></p>
                    </div>
                {% endif %}
			{% endfor %}
    		</div>
    	</div>
    </section>

    <section class="ftco-section">
    	<div class="container">
				<div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
          	<span class="subheading">Today's Deals</span>
            <h2 class="mb-4">Our Products</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
          </div>
        </div>   		
    	</div>
    	<div class="container">
    		<div class="row">
    			{% for Vegtables in vegtable %}
					{% if Vegtables.Discount > 0 %}
						<div class="col-md-6 col-lg-3 ftco-animate">
							<div class="product">
								<a href="{% url 'shop:single_product' pk=Vegtables.pk %}" class="img-prod"><img class="img-fluid" src="/{{ Vegtables.image }}" alt="Colorlib Template">
								{% if Vegtables.Discount > 0 %}
									<span class="status">{{ Vegtables.Discount }}%</span>
								{% endif %}
									<div class="overlay"></div>
								</a>
								<div class="text py-3 pb-4 px-3 text-center">
									<h3><a href="#">{{ Vegtables.title }}</a></h3>
									<div class="d-flex">
										<div class="pricing">
										{% if Vegtables.Discount > 0 %}
											<p class="price"><span class="mr-2 price-dc">${{ Vegtables.prise }}</span><span class="price-sale">${{ Vegtables.discount_prise }}</span></p>
										{% else %}
											<p class="price"><span>${{ Vegtables.prise }}</span></p>
										{% endif %}
										</div>
									</div>
									<div class="bottom-area d-flex px-3">
										<div class="m-auto d-flex">
											<a href="{% url 'shop:single_product' pk=Vegtables.pk %}" class="add-to-cart d-flex justify-content-center align-items-center text-center">
												<span><i class="ion-ios-menu"></i></span>
											</a>
											<a href="{% url 'cart:addone' pk=Vegtables.pk pg=3 %}" class="buy-now d-flex justify-content-center align-items-center mx-1">
												<span><i class="ion-ios-cart"></i></span>
											</a>
											{% for Whislist in wishlist %}
												{% if user ==  Whislist.user %}
													{% if Vegtables ==  Whislist.vegtable %}
														{% if Whislist.wish ==  True %}
															<style>
																a[href="{% url 'cart:addwish' pk=Vegtables.pk pg=3 %}"] {
																	color:#CB4335 !important;
																}
															</style>
														{% endif %}
													{% endif %}
												{% endif %}
											{% endfor %}
											<a href="{% url 'cart:addwish' pk=Vegtables.pk pg=3 %}" class="heart d-flex justify-content-center align-items-center ">
												<span><i class="ion-ios-heart"></i></span>
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					{% endif %}
				{% endfor %}
    		</div>
    	</div>
    </section>

{% endblock content %}