vegefoods/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp, name='signup'),
]

vegefoods/cart/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    # path('', views.CartPage.as_view(), name='cart'),
    path('', views.view_cart, name='cart'),
    url(r"add/(?P<pk>\d+)(?P<qnt>\d+)/$",views.add_to_cart,name="add_to_cart"),
    path('wishlist/', views.WhishlistPage.as_view(), name='wishlist'),
    path('thanks/', views.ThanksPage, name='thanks'),
    url(r"remove/(?P<pk>\d+)/$",views.remove_from_cart.as_view(),name="remove"),
    url(r"addone/(?P<pk>\d+)/(?P<pg>\d+)/$",views.add_one_to_cart.as_view(),name="addone"),
    url(r"addwish/(?P<pk>\d+)/(?P<pg>\d+)/$",views.add_to_wishlist.as_view(),name="addwish"),
]

vegefoods/shop/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


app_name = 'shop'

urlpatterns = [
    path('', views.ShopPage, name='shop'),
    # path('single_product/', views.ShopPage.as_view(), name='single_product'),
    url(r"single_product/(?P<pk>\d+)/$",views.SingleProduct,name="single_product"),
]

vegefoods/vegefoods/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage, name='home'),
    path('admin/', admin.site.urls),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('checkout/', views.checkoutPage.as_view(), name='checkout'),
    path('contact/', views.contactPage.as_view(), name='contact'),
    path('shop/', include('shop.urls', namespace="shop")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
]

vegefoods/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Vegtables
# Create your models here.

class Wishlist(models.Model):
    user = models.ForeignKey(User, related_name="user",on_delete=models.CASCADE)
    vegtable = models.ForeignKey(Vegtables,related_name='vegtable',on_delete=models.CASCADE)
    wish = models.BooleanField()

    def __str__(self):
        temp_str = self.user.__str__() + " / " + self.vegtable.__str__()
        return temp_str

    class Meta:
        ordering = ["user"]

vegefoods/cart/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, RedirectView, ListView
from braces.views import SelectRelatedMixin
from django.urls import reverse
from shop.models import Vegtables
from cart.models import Wishlist

class CartPage(TemplateView):
    template_name = 'cart.html'

class WhishlistPage(ListView):
    model = Wishlist
    template_name = 'wishlist.html'

# class ThanksPage(TemplateView):
#     del request.session['cart']
#     template_name = 'thanks.html'

def ThanksPage(request):
    if 'cart' in request.session:
        del request.session['cart']
    return render(request,'thanks.html')
    
def view_cart(request):
    vegtable = Vegtables.objects.all
    args = {'vegtable':vegtable}
    return render(request,'cart.html',args)

def add_to_cart(request, pk=None, qnt=None):
    if 'cart' not in request.session:
        request.session['cart'] = {}

    if pk:
        if qnt:
            cart = request.session.get('cart', {})
            if not pk in cart:
                cart[pk] = qnt
            else:
                cart[pk] = int(cart[pk]) + int(qnt)
                
            request.session['cart'] = cart

            vegtable = Vegtables.objects.all
            args = {'vegtable':vegtable, 'pk':pk}
            return render(request,'single_product.html',args)
        else:
            return render(request,'shop.html')
    else:
        return render(request,'shop.html')

# def remove_from_cart(request, pk=None):
#     if 'cart' in request.session and pk:
#         cart_dict = request.session['cart']
#         print(cart_dict)
#         del cart_dict[pk]
#         request.session['cart'] = cart_dict
#         print(cart_dict)

#     return render(request,'cart.html')

class add_one_to_cart(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        pg = self.kwargs.get("pg")
        red_url = "shop:shop"
        if pg == "1":
            red_url = "home"
        elif pg == "2":
            red_url = "shop:shop"
        elif pg == "3":
            red_url = "shop:single_product"
            
        return reverse(red_url)

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")
        if pk:
            cart = request.session.get('cart', {})
            if not pk in cart:
                cart[pk] = 1
            else:
                cart[pk] = int(cart[pk]) + 1
                    
            request.session['cart'] = cart

        return super().get(request, *args, **kwargs)

class remove_from_cart(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("cart:cart")

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")
        if 'cart' in request.session and pk:
            cart_dict = request.session['cart']
            del cart_dict[pk]
            request.session['cart'] = cart_dict

        return super().get(request, *args, **kwargs)

class add_to_wishlist(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        pg = self.kwargs.get("pg")
        red_url = "shop:shop"
        if pg == "1":
            red_url = "home"
        elif pg == "2":
            red_url = "shop:shop"
        elif pg == "3":
            red_url = "shop:single_product"
        elif pg == "4":
            red_url = "cart:wishlist"
                        
        return reverse(red_url)

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get("pk")
        try:
            print(Wishlist.objects.get(user=request.user, vegtable=Vegtables.objects.get(pk=pk)))
            if Wishlist.objects.filter(user=request.user, vegtable=Vegtables.objects.get(pk=pk), wish=True):
                Wishlist.objects.filter(user=request.user, vegtable=Vegtables.objects.get(pk=pk), wish=True).update(wish=False)
            else:
                Wishlist.objects.filter(user=request.user, vegtable=Vegtables.objects.get(pk=pk), wish=False).update(wish=True)
        except:
            temp_wish = Wishlist.objects.get_or_create(user=request.user, vegtable=Vegtables.objects.get(pk=pk), wish=True)[0]
            temp_wish.save()

        return super().get(request, *args, **kwargs)

vegefoods/cart/templates/cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block content %}
    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>Product name</th>
						        <th>Detail</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>
							{% for key, value in request.session.cart.items %}
								{% if 'cart' in request.session %}
									{% for Vegtables in vegtable %}
										{% if Vegtables.pk|add:"0" == key|add:"0" %}
											<tr class="text-center">
												<td class="product-remove"><a href={% url 'cart:remove' pk=Vegtables.pk %}><span class="ion-ios-close"></span></a></td>
												
												<td class="image-prod"><a href="{% url 'shop:single_product' pk=Vegtables.pk %}"><div class="img" style="background-image:url(/{{ Vegtables.image }});"></div></a></td>
												
												<td class="product-name">
													<h3>{{ Vegtables.title }}</h3>
													<p>{{ Vegtables.detail }}</p>
												</td>
												
													{% if Vegtables.Discount > 0 %}
														<td class="price"><span name="subtotal" class="mr-2 price-dc" style="text-decoration: line-through;color: #b3b3b3;">${{ Vegtables.prise }}</span><span class="price-sale">${{ Vegtables.discount_prise }}</span></td>
													{% else %}
														<td class="price"><span name="subtotal">${{ Vegtables.prise }}</span></td>
													{% endif %}

												<td class="quantity">
													<div class="input-group mb-3">
													<input type="text" name="quantity" class="quantity form-control input-number" value="{{ value }}" min="1" max="100" readonly>
													</div>
												</td>
												
												<td name="total" class="total">${% widthratio  Vegtables.discount_prise 1 value %}</td>
												{% comment %} <td class="total">$awd</td> {% endcomment %}
											</tr><!-- END TR-->
										{% endif %}
									{% endfor %}
								{% endif %}
							{% endfor %}
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		<div class="row justify-content-end">
				{% if user.is_authenticated %}
							<div class="col-lg-8 mt-5 cart-wrap ftco-animate">
								<div class="cart-total mb-3">
									<h3>State/country:</h3>
									<p>{{ user.profile.state_country }}</p>
								</div>
								<div class="cart-total mb-3">
									<h3>Address:</h3>
									<p>{{ user.profile.address }}</p>
								</div>
								<div class="cart-total mb-3">
									<h3>Phone number:</h3>
									<p>{{ user.profile.phone_number }}</p>
								</div>
							</div>
				{% else %}
					<div class="col-lg-8 mt-5 cart-wrap ftco-animate">
						<div class="cart-total mb-3">
							<h3 align="center">Please Login to your account</h3>
						</div>
						<p align="center"><a href="{% url 'accounts:login' %}" class="btn btn-primary py-3 px-4">Login</a></p>
					</div>

				{% endif %}



    			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
    					<h3>Cart Totals</h3>
						{% if 'cart' in request.session %}
							{% if request.session.cart.items %}
								<p class="d-flex">
									<span>Subtotal</span>
									<span id="subtotal_text">$0</span>
								</p>
								<p class="d-flex">
									<span>Delivery</span>
									<span>$0</span>
								</p>
								<p class="d-flex">
									<span>Discount</span>
									<span id="discount_text">$0</span>
								</p>
								<hr>
								<p class="d-flex total-price">
									<span>Total</span>
									<span id="total_text">$0</span>
								</p>
							{% else %}
								<h3>There is no items in cart</h3>
							{% endif %}
						{% else %}
							<h3>There is no items in cart</h3>
						{% endif %}
						</div>
					{% if 'cart' in request.session %}
						{% if request.session.cart.items %}
							{% if user.is_authenticated %}
								<p><a href="{% url 'cart:thanks' %}" class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
							{% endif %}
						{% endif %}
					{% endif %}
    			</div>
    		</div>
			</div>
		</section>

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

	<style>
		.ftco-cart .form-group .form-control {
			text-align: left;
			padding-left: 20px;
			}
	</style>
	<script>
		window.onload = function() {
			var subTotal = 0
			var els = document.getElementsByName('subtotal')
			var qnt = document.getElementsByName('quantity')
			for (var i=0, len = els.length; i<len; i++) {
				subTotal += parseFloat(els[i].innerHTML.substr(1)) * parseFloat(qnt[i].value)
			}
			

			var total = 0
			var els = document.getElementsByName('total')
			for (var i=0, len = els.length; i<len; i++) {
				total += parseFloat(els[i].innerHTML.substr(1))
			}
			
			discount = '$' + (subTotal - total)
			document.getElementById("discount_text").innerHTML = discount;

			subTotal = '$' + subTotal
			document.getElementById("subtotal_text").innerHTML = subTotal;

			total = '$' + total
			document.getElementById("total_text").innerHTML = total;

		}
	</script>
{% endblock content %}

vegefoods/cart/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<br><br><br>
<div class="row justify-content-center">
    <div class="col-4">
        <div class="card">
            <div class="card-body">
	          <p align="center">Thanks for your purchase</a></p>
            </div>
        </div>
    </div>
</div>
<br><br><br>
{% endblock %}

vegefoods/cart/templates/wishlist.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
				{% if user.is_authenticated %}
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
							  	<th>&nbsp;</th>
						        <th>Product name</th>
						        <th>Detail</th>
						        <th>Price</th>
						      </tr>
						    </thead>
						    <tbody>
							{% for Wishlist in object_list %}
								{% if Wishlist.wish %}
								<tr class="text-center">
									<td class="product-remove"><a href={% url 'cart:addwish' pk=Wishlist.vegtable.pk pg=4 %}><span class="ion-ios-close"></span></a></td>

									<td class="image-prod"><a href="{% url 'shop:single_product' pk=Wishlist.vegtable.pk %}"><div class="img" style="background-image:url(/{{ Wishlist.vegtable.image }});"></div></a></td>
									
									<td class="product-name">
										<h3>{{ Wishlist.vegtable.title }}</h3>
										<p>{{ Wishlist.vegtable.detail }}</p>
									</td>

									{% if Wishlist.vegtable.Discount > 0 %}
										<td class="price"><span name="subtotal" class="mr-2 price-dc" style="text-decoration: line-through;color: #b3b3b3;">${{ Wishlist.vegtable.prise }}</span><span class="price-sale">${{ Wishlist.vegtable.discount_prise }}</span></td>
									{% else %}
										<td class="price"><span name="subtotal">${{ Wishlist.vegtable.prise }}</span></td>
									{% endif %}
								</tr><!-- END TR-->
								{% endif %}
							{% endfor %}
						    </tbody>
						</table>
					</div>
				{% endif %}
    			</div>
    		</div>
			</div>
		</section>
{% endblock content %}